### ISSUE TITLE
🔶 Add RSS feed for superfans™

### ISSUE THREAD

**Issue by tatianamac** [xdesro/vogue#16]
So we can add you to yet another platform ...

**Comment by xdesro** [comment]
How do you envision this being implemented? Is there a format that works better than https://henry.codes/rss.xml ? Am I doing it wrong?

**Comment by xdesro** [comment]
Resolved by 1b36ad2f453135326c6f99280e956dc135c4f27b! Feed lives at https://henry.codes/rss.xml.
